name = "Isosuite"
uuid = "4e0cf86c-8ca5-4e68-a38e-9d6c92424124"
authors = ["Yunlong Lian <algorithm.lian@gmail.com>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"


[compat]
julia = "1"
